p1:
	python src/part1.py < input/input

p2:
	python src/part2.py $$(wc -l input/input) < input/input

p2_alt:
	python src/part2.alt.py < input/input

p1_test:
	python src/part1.py < input/small

p2_test:
	python src/part2.py $$(wc -l input/small) < input/small

p2_alt_test:
	python src/part2.alt.py < input/small

